/* =============================================================================
   CIRURGIAS.JS  —  BANCO DE DESCRICOES OPERATORIAS
   =============================================================================

   Este arquivo guarda SOMENTE os dados das cirurgias. O motor do site (interface,
   busca, preview, copiar) fica no app e NUNCA precisa ser editado para adicionar
   uma cirurgia nova. Para adicionar, basta acrescentar um objeto ao final do
   array SURGERIES, antes do "];".

   -----------------------------------------------------------------------------
   COMO FUNCIONA O "CORPO" (texto com lacunas)
   -----------------------------------------------------------------------------
   O campo "corpo" e a descricao inteira em texto. Cada quebra de linha vira uma
   linha da descricao. Onde algo pode mudar, voce envolve em colchetes duplos:

        [[chave | opcoes]]

   A chave e um identificador curto (ex: lado, anestesia, haste). O que vem
   depois da barra "|" define o tipo do campo:

   1) SELECT (lista suspensa) -> duas ou mais opcoes separadas por virgula.
      A primeira opcao e o padrao.
        Ex: [[lado | DIREITO, ESQUERDO]]
        Ex: [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL, BLOQUEIO PLEXULAR]]

   2) TEXTO (digitavel) -> um unico valor depois da barra vira o texto padrao.
        Ex: [[fio | NYLON 4-0]]
        Ex: [[volume | 140]]
      Se o texto padrao tiver VIRGULAS (e voce NAO quer uma lista), use "~"
      logo apos a barra para o texto ser usado tal e qual:
        Ex: [[fechamento |~ 2 VICRYL 1.0, 2 VICRYL 2.0 E 3 NYLON 3.0]]

   3) TEXTO COM ATALHOS (pills) -> use "+" logo apos a barra. As opcoes viram
      botoes clicaveis de preenchimento rapido, e a primeira ja vem preenchida.
      O usuario ainda pode digitar manualmente.
        Ex: [[haste |+ 10X360, 11X170, 9X330]]

   4) NUMERO -> use "#" logo apos a barra. Abre teclado numerico no celular.
        Ex: [[parafusos |# 2]]

   5) RECITAR A MESMA LACUNA -> depois de definir uma chave uma vez, repita
      so [[chave]] (sem barra) que ela usa o mesmo campo e atualiza junto.
        Ex: ...MEMBRO INFERIOR [[lado]]...  (reaproveita o "lado" ja definido)

   6) LINHA OPCIONAL (aparece ou some) -> deixe a primeira opcao VAZIA. Quando
      a opcao vazia estiver escolhida, a linha inteira some da descricao.
        Ex: [[dreno | , COLOCACAO DE DRENO TIPO SUCTOR 3.2MM EM FERIDA OPERATORIA]]
        (a opcao vazia aparece como "—" na lista)

   7) ROTULO BONITO (opcional) -> para mostrar um nome diferente da chave, use "=".
        Ex: [[acetabular=Componente acetabular | 50 MM, 52 MM]]

   -----------------------------------------------------------------------------
   BLOCOS REUTILIZAVEIS
   -----------------------------------------------------------------------------
   Trechos que se repetem em quase toda cirurgia ficam em BLOCOS (abaixo). No
   corpo, chame com chaves duplas curvas: {{assepsia}}, {{repai}} etc.
   Assim, se um padrao mudar, muda em um lugar so.

   -----------------------------------------------------------------------------
   CAMPOS DE CADA CIRURGIA (objeto)
   -----------------------------------------------------------------------------
     id       : string unica          (ex: 'atj')
     name     : nome no card           (ex: 'Artroplastia Total de Joelho')
     category : categoria              (Quadril, Joelho, Ombro, Mao e Punho,
                                        Pe e Tornozelo, Trauma, Oncologia, Outros)
     color    : cor do ponto do card   (quadril, joelho, ombro, trauma, mao,
                                        pe, onco, livre)
     corpo    : a descricao com lacunas [[ ]] e blocos {{ }}

   (opcional) freeOnly: true  -> abre direto em Texto Livre, sem campos.

   -----------------------------------------------------------------------------
   MODELO PRONTO PARA COPIAR  (duplique e preencha)
   -----------------------------------------------------------------------------
   {
     id: 'minha_cirurgia',
     name: 'Nome Que Aparece No Card',
     category: 'Trauma',
     color: 'trauma',
     corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]]
{{assepsia}}
GARROTEAMENTO DO MEMBRO INFERIOR [[lado | DIREITO, ESQUERDO]]
INCISAO SOBRE O FOCO DE FRATURA DO MEMBRO INFERIOR [[lado]]
FIXACAO COM [[parafusos |# 2]] PARAFUSOS
{{lavagem}}
{{rafia}}
{{curativo}}
{{repai}}`
   },

   ============================================================================ */

const BLOCOS = {
  assepsia:
`ASSEPSIA E ANTISSEPSIA
COLOCACAO DE CAMPOS ESTEREIS CONFORME ROTINA ORTOPEDICA`,
  disseccao:
`DISSECCAO POR PLANOS E HEMOSTASIA CUIDADOSA`,
  lavagem:
`LAVAGEM COM SOLUCAO FISIOLOGICA`,
  lavagemExaustiva:
`LAVAGEM EXAUSTIVA COM SOLUCAO FISIOLOGICA`,
  rafia:
`RAFIA POR PLANOS`,
  suturaPlanos:
`SUTURA POR PLANOS`,
  curativo:
`CURATIVO ESTERIL`,
  fluoroFinalImplante:
`CONTROLE FLUOROSCOPICO FINAL NAS INCIDENCIAS AP E PERFIL CONFIRMANDO REDUCAO E POSICIONAMENTO ADEQUADO DO IMPLANTE`,
  repai:
`AOS CUIDADOS DA REPAI`
};

const SURGERIES = [

  /* ===========================  QUADRIL  =================================== */
  {
    id: 'atq_cimentada_colo',
    name: 'ATQ Cimentada / Fratura do Colo do Femur',
    category: 'Quadril',
    color: 'quadril',
    corpo: `
PACIENTE EM DECUBITO LATERAL [[decubito_contra | DIREITO, ESQUERDO]] SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]]
POSICIONAMENTO E FIXACAO DO PACIENTE EM MESA CIRURGICA COM SUPORTES LATERAIS
{{assepsia}}
ACESSO POSTEROLATERAL DO QUADRIL [[lado | ESQUERDO, DIREITO]]
{{disseccao}}
EXPOSICAO DOS ROTADORES EXTERNOS CURTOS
REPARO DO MUSCULO PIRIFORME COM [[fio_piriforme | VICRYL 2.0]]
CAPSULOTOMIA POSTERIOR COM EXPOSICAO DA ARTICULACAO
LUXACAO CONTROLADA DA CABECA FEMORAL
OSTEOTOMIA DO COLO FEMORAL
RESSECCAO DA CABECA FEMORAL
FRESAGEM PROGRESSIVA DO ACETABULO ATE TAMANHO DEFINITIVO
CIMENTACAO DO ACETABULO COM CIMENTO ORTOPEDICO
POSICIONAMENTO DO COMPONENTE ACETABULAR [[acetabular=Componente acetabular | 50 MM, 52 MM, 48 MM, 54 MM]] COM 15 GRAUS DE ANTEVERSAO E 45 GRAUS DE ABDUCAO
FIXACAO COMPLEMENTAR DO COMPONENTE ACETABULAR COM [[parafusos_acetab=Parafusos acetabulares | 1 PARAFUSO ACETABULAR DE 25 MM, 2 PARAFUSOS ACETABULARES DE 25 MM E 20 MM, ]]
FRESAGEM PROGRESSIVA DO CANAL MEDULAR FEMORAL ATE DIMENSIONAMENTO ADEQUADO
LAVAGEM EXAUSTIVA DO CANAL FEMORAL COM SOLUCAO FISIOLOGICA SOB PRESSAO
CIMENTACAO RETROGRADA DO CANAL FEMORAL COM CIMENTO ORTOPEDICO [[cimento=Marca cimento | LEPINE]] UTILIZANDO PISTOLA DE CIMENTACAO COM TECNICA DE TERCEIRA GERACAO
INSERCAO DA HASTE FEMORAL [[haste=Haste femoral |+ NUMERO 1, NUMERO 0, NUMERO 2, NUMERO 3]] COM COLO STANDARD
AGUARDADO ENDURECIMENTO DO CIMENTO
INSERCAO DA CABECA FEMORAL [[offset=Offset / cabeca | OFFSET -4, OFFSET -2, OFFSET 0, 32 MM OFFSET -4]]
REDUCAO DA PROTESE COM TESTE DE ESTABILIDADE, AMPLITUDE DE MOVIMENTO E COMPRIMENTO DO MEMBRO
CONFIRMADA ESTABILIDADE SATISFATORIA SEM SINAIS DE LUXACAO NAS MANOBRAS DE ESTRESSE
{{lavagemExaustiva}}
REPARO DA CAPSULA POSTERIOR E TENDOES ROTADORES EXTERNOS CURTOS
{{suturaPlanos}}
SUTURA DE PELE COM [[fio_pele | NYLON]]
{{curativo}}
{{repai}}`
  },
  {
    id: 'revisao_atq_femoral',
    name: 'Revisao de ATQ / Componente Femoral Cimentado',
    category: 'Quadril',
    color: 'quadril',
    corpo: `
PACIENTE EM DECUBITO LATERAL [[decubito_contra | ESQUERDO, DIREITO]] SOB [[anestesia | ANESTESIA GERAL, RAQUIANESTESIA]]
{{assepsia}}
ACESSO POSTEROLATERAL DO QUADRIL [[lado | DIREITO, ESQUERDO]]
{{disseccao}}
CAPSULOTOMIA POSTERIOR COM EXPOSICAO DA ARTICULACAO
LUXACAO CONTROLADA DA CABECA FEMORAL
IDENTIFICACAO DOS COMPONENTES PROTETICOS PREVIAMENTE INSTALADOS
COMPONENTE ACETABULAR AVALIADO, APRESENTANDO POSICIONAMENTO E ESTABILIDADE ADEQUADOS, MANTIDO SEM INTERCORRENCIAS
RETIRADA DA HASTE FEMORAL ANTIGA COM AUXILIO DE INSTRUMENTAL ESPECIFICO PARA REVISAO
LIMPEZA CUIDADOSA DO CANAL FEMORAL COM REMOCAO DE CIMENTO RESIDUAL E TECIDO FIBROSO
FRESAGEM PROGRESSIVA DO CANAL FEMORAL ATE DIMENSIONAMENTO ADEQUADO PARA O NOVO IMPLANTE
LAVAGEM EXAUSTIVA DO CANAL FEMORAL COM SOLUCAO FISIOLOGICA SOB PRESSAO
CIMENTACAO DO CANAL FEMORAL COM POLIMETILMETACRILATO COM TECNICA DE TERCEIRA GERACAO
INSERCAO DA NOVA HASTE FEMORAL [[haste=Haste femoral |+ 22X230]] MM COM AUXILIO DE GUIA INTRODUTOR EM POSICAO DE VARO E RETROVERSAO ADEQUADOS
AGUARDADO ENDURECIMENTO DO CIMENTO
INSERCAO DA CABECA FEMORAL [[cabeca=Cabeca femoral |+ 32 MM OFFSET -4]]
REDUCAO DA PROTESE COM TESTE DE ESTABILIDADE, AMPLITUDE DE MOVIMENTO E COMPRIMENTO DO MEMBRO
CONFIRMADA ESTABILIDADE SATISFATORIA SEM SINAIS DE LUXACAO NAS MANOBRAS DE ESTRESSE
{{lavagemExaustiva}}
REPARO DA CAPSULA POSTERIOR E TENDOES PELVITROCANTERICOS
{{suturaPlanos}}
SUTURA DE PELE
{{curativo}}
{{repai}}`
  },
  {
    id: 'luxacao_coxofemoral_tracao',
    name: 'Reducao Incruenta de Luxacao Coxofemoral / Tracao Esqueletica',
    category: 'Quadril',
    color: 'quadril',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | ANESTESIA GERAL, SEDACAO]]
{{assepsia}}
REALIZADA REDUCAO INCRUENTA DA LUXACAO COXOFEMORAL POR MANOBRA DE ALLIS COM TRACAO LONGITUDINAL DO MEMBRO INFERIOR EM FLEXAO DE QUADRIL A 90 GRAUS, ADUCAO E ROTACAO INTERNA PROGRESSIVA
CONTROLE FLUOROSCOPICO CONFIRMANDO REDUCAO CONCENTRICA DA CABECA FEMORAL NO ACETABULO
IDENTIFICADA AO FLUOROSCOPIO FRATURA DO ACETABULO ASSOCIADA
AVALIACAO DA ESTABILIDADE ARTICULAR SOB CONTROLE FLUOROSCOPICO COM MANOBRAS DE ESTRESSE
ASSEPSIA E ANTISSEPSIA DO MEMBRO INFERIOR PARA INSTALACAO DE TRACAO ESQUELETICA
INSERCAO DE PINO DE TRACAO ESQUELETICA TRANSCONDILIANO FEMORAL DISTAL SOB TECNICA ASSEPTICA
INSTALACAO DE SISTEMA DE TRACAO ESQUELETICA COM CARGA DE APROXIMADAMENTE 10% DO PESO CORPORAL DO PACIENTE
CONTROLE FLUOROSCOPICO FINAL CONFIRMANDO MANUTENCAO DA REDUCAO E ALINHAMENTO SATISFATORIO DO ACETABULO SOB TRACAO
CURATIVO ESTERIL NO SITIO DE INSERCAO DO PINO DE TRACAO
{{repai}}`
  },
  {
    id: 'reducao_luxacao_atq',
    name: 'Reducao Incruenta de Luxacao de ATQ',
    category: 'Quadril',
    color: 'quadril',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | SEDACAO, ANESTESIA GERAL]]
REALIZADA REDUCAO INCRUENTA DA LUXACAO DA ARTROPLASTIA TOTAL DE QUADRIL POR MANOBRA FECHADA COM TRACAO LONGITUDINAL DO MEMBRO INFERIOR, FLEXAO, ADUCAO E ROTACAO INTERNA PROGRESSIVA
CONTROLE FLUOROSCOPICO CONFIRMANDO REDUCAO E REPOSICIONAMENTO CONCENTRICO DOS COMPONENTES PROTETICOS
AVALIACAO DA ESTABILIDADE SOB CONTROLE FLUOROSCOPICO COM MANOBRAS DE ESTRESSE
CONFIRMADA ESTABILIDADE SATISFATORIA DOS COMPONENTES AO FINAL DO PROCEDIMENTO
{{repai}}`
  },

  /* ===========================  JOELHO  =================================== */
  {
    id: 'atj',
    name: 'Artroplastia Total de Joelho',
    category: 'Joelho',
    color: 'joelho',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]]
ANTISSEPSIA E ASSEPSIA DE MEMBRO INFERIOR [[lado | ESQUERDO, DIREITO]] E COLOCACAO DE CAMPOS ESTEREIS
INSTALADO ELETROCAUTERIO E ASPIRADOR COM FILTRO
POSICIONADO CAMPO ADESIVO
ACESSO ANTERIOR COM ARTROTOMIA PARAPATELAR MEDIAL EM JOELHO [[lado]]
RETIRADA DE OSTEOFITOS E SINOVECTOMIA
CONFECCAO DE CORTE FEMORAL DE [[corte_femoral | 9MM]] E [[valgo | 5 GRAUS]] DE VALGO COM AUXILIO DE GUIA INTRAMEDULAR
CONFECCAO DE CORTE TIBIAL COM GUIA INTRAMEDULAR, [[corte_tibial | 10MM]] DO PLATO LATERAL
CONFECCAO DE CORTES ANTERIOR, POSTERIOR E CHANFRO FEMORAL COM [[rotacao | 3 GRAUS]] DE ROTACAO EXTERNA E CONFECCAO DA CAIXA FEMORAL
TESTE DE COMPONENTES COM FLEXOEXTENSAO ADEQUADA, TRACKING PATELAR OK E VALGO E VARO ESTAVEL
RETIRADO TESTES E REALIZADO LAVAGEM EXAUSTIVA COM SORO FISIOLOGICO
INSUFLADO GARROTE
CIMENTACAO DE COMPONENTES DEFINITIVOS: [[cimento | 1 CIMENTO SEM ANTIBIOTICO]], FEMUR [[femur |# 4]], TIBIA [[tibia |# 3]] E LINER [[liner |# 10]]
VERIFICADA ESTABILIDADE APOS SECAGEM DO CIMENTO
[[dreno | , COLOCACAO DE DRENO TIPO SUCTOR 3.2MM EM FERIDA OPERATORIA]]
VERIFICADA HEMOSTASIA
FECHAMENTO POR PLANOS COM [[fechamento |~ 2 VICRYL 1.0, 2 VICRYL 2.0 E 3 NYLON 3.0]]
DESINSUFLADO GARROTE
{{curativo}}
COMPONENTE VASCULAR SEM ALTERACOES
{{repai}}`
  },
  {
    id: 'lca_ganso',
    name: 'Reconstrucao de LCA / Pata de Ganso / Meniscectomia / Artroscopia',
    category: 'Joelho',
    color: 'joelho',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]] SEM GARROTEAMENTO INICIAL
{{assepsia}}
POSICIONAMENTO DE COXIM SOB O PE [[lado | ESQUERDO, DIREITO]]
POSICIONAMENTO DE POSTE CIRURGICO LATERAL PARA APOIO E REALIZACAO DE ESTRESSE EM VARO DO JOELHO [[lado]]
INCISAO SOBRE A REGIAO DA PATA DE GANSO NA FACE ANTEROMEDIAL DA TIBIA PROXIMAL [[lado]]
{{disseccao}}
IDENTIFICACAO DOS TENDOES DOS MUSCULOS GRACIL E SEMITENDINEO
RETIRADA DO ENXERTO DE TENDOES DA PATA DE GANSO COM AUXILIO DE TENOTOMO ESPECIFICO
PREPARO DO ENXERTO EM MESA AUXILIAR COM SUTURAS DAS EXTREMIDADES E MENSURACAO DO DIAMETRO E COMPRIMENTO
GARROTEAMENTO DO MEMBRO INFERIOR [[lado]]
ESTABELECIMENTO DOS PORTAIS ANTEROLATERAL E ANTEROMEDIAL
INTRODUCAO DA OPTICA E INVENTARIO ARTICULAR COMPLETO
IDENTIFICADA LESAO MENISCAL
MENISCECTOMIA PARCIAL DO MENISCO ACOMETIDO COM REGULARIZACAO DAS BORDAS REMANESCENTES
IDENTIFICADA LESAO COMPLETA DO LIGAMENTO CRUZADO ANTERIOR COM AUSENCIA DE FUNCIONALIDADE
DESBRIDAMENTO DO COTO REMANESCENTE DO LCA COM AUXILIO DE SHAVER MOTORIZADO
PREPARO DO TUNEL TIBIAL COM GUIA TIBIAL ESPECIFICA SOB VISUALIZACAO ARTROSCOPICA
PREPARO DO TUNEL FEMORAL POR TECNICA [[tecnica | TRANSPORTAL, TRANSTIBIAL]]
PASSAGEM DO ENXERTO PELOS TUNEIS FEMORAL E TIBIAL
FIXACAO DO ENXERTO COM PARAFUSO DE INTERFERENCIA [[parafuso=Parafuso interferencia |+ BIOSURE HA 6X20 MM]] NO TUNEL FEMORAL
TESTE DE TENSIONAMENTO DO ENXERTO COM CICLAGEM DO JOELHO
FIXACAO DO ENXERTO COM SEGUNDO PARAFUSO DE INTERFERENCIA [[parafuso]] NO TUNEL TIBIAL COM JOELHO EM EXTENSAO
CONFIRMADA ESTABILIDADE ANTEROPOSTERIOR ADEQUADA AO TESTE DE LACHMAN ARTROSCOPICO
LAVAGEM ARTICULAR EXAUSTIVA COM SOLUCAO FISIOLOGICA
RETIRADA DOS PORTAIS
{{suturaPlanos}}
SUTURA DE PELE COM NYLON
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'retirada_fixador_manipulacao',
    name: 'Retirada de Fixador Externo Transarticular / Manipulacao Articular',
    category: 'Joelho',
    color: 'joelho',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]]
{{assepsia}}
RETIRADA DOS PINOS DE SCHANZ DO FIXADOR EXTERNO TRANSARTICULAR PREVIAMENTE INSTALADO
REMOCAO DO CONJUNTO DO FIXADOR EXTERNO TRANSARTICULAR
LIMPEZA E DESBRIDAMENTO DOS SITIOS DE INSERCAO DOS PINOS
MANIPULACAO ARTICULAR DO JOELHO [[lado | ESQUERDO, DIREITO]] SOB ANESTESIA
IDENTIFICADA GRANDE RIGIDEZ ARTICULAR COM IMPORTANTE LIMITACAO DA AMPLITUDE DE MOVIMENTO
GANHO PARCIAL DE FLEXAO DO JOELHO [[lado]] APOS MANIPULACAO
ABORDAGEM DA FERIDA PREVIA EM FACE ANTERIOR DO JOELHO [[lado]]
LIMPEZA EXAUSTIVA DA FERIDA COM SOLUCAO FISIOLOGICA SOB PRESSAO
SUTURA DA FERIDA COM NYLON
{{curativo}}
{{repai}}`
  },

  /* ============================  OMBRO  ================================== */
  {
    id: 'latarjet',
    name: 'Instabilidade Glenoumeral Anterior / Latarjet',
    category: 'Ombro',
    color: 'ombro',
    corpo: `
PACIENTE EM [[posicao | DECUBITO DORSAL, CADEIRA DE PRAIA]] SOB [[anestesia | ANESTESIA GERAL, BLOQUEIO PLEXULAR]]
{{assepsia}}
[[garrote | SEM GARROTEAMENTO DO MEMBRO SUPERIOR, GARROTEAMENTO DO MEMBRO SUPERIOR]] [[lado | DIREITO, ESQUERDO]]
INCISAO LONGITUDINAL DELTOPEITORAL [[lado]]
DISSECCAO POR PLANOS COM IDENTIFICACAO E PRESERVACAO DA VEIA CEFALICA LATERALMENTE
ABERTURA DO INTERVALO DELTOPEITORAL COM EXPOSICAO DO MUSCULO SUBESCAPULAR
[[subescapular | TENOTOMIA DO SUBESCAPULAR NO TERCO INFERIOR, TENOTOMIA HORIZONTAL DO SUBESCAPULAR, SPLIT DO SUBESCAPULAR]]
CAPSULOTOMIA ANTERIOR COM EXPOSICAO DO REBORDO GLENOIDAL ANTERIOR
IDENTIFICACAO E CONFIRMACAO DA LESAO OSSEA DO REBORDO GLENOIDAL ANTERIOR
PREPARO DO REBORDO GLENOIDAL ANTERIOR COM DECORTICACAO DA SUPERFICIE RECEPTORA
IDENTIFICACAO DO PROCESSO CORACOIDE COM DISSECCAO DA INSERCAO DO LIGAMENTO CORACOACROMIAL
OSTEOTOMIA DA BASE DO PROCESSO CORACOIDE COM PRESERVACAO DA INSERCAO DO MUSCULO CORACOBRAQUIAL E CABECA CURTA DO BICEPS
PREPARO DO ENXERTO CORACOIDE COM REGULARIZACAO DA SUPERFICIE DE CONTATO
POSICIONAMENTO DO ENXERTO CORACOIDE NO REBORDO GLENOIDAL ANTERIOR RENTE A SUPERFICIE ARTICULAR
FIXACAO DO ENXERTO COM [[fixacao | 2 PARAFUSOS CORTICAIS, 2 PARAFUSOS CANULADOS]]
CONTROLE FLUOROSCOPICO CONFIRMANDO POSICIONAMENTO ADEQUADO DO ENXERTO E DOS PARAFUSOS
REPARO DA CAPSULA ANTERIOR SOBRE O ENXERTO
REPARO DO SUBESCAPULAR COM [[reparo_sub | SUTURA TRANSOSSEA, FIO ABSORVIVEL]]
TESTE DE ESTABILIDADE COM MANOBRAS DE ABDUCAO E ROTACAO EXTERNA
{{lavagemExaustiva}}
{{suturaPlanos}}
SUTURA DE PELE COM NYLON
IMOBILIZACAO EM [[imobilizacao | TIPOIA, TIPOIA COM CINTO DE ROTACAO INTERNA]]
{{curativo}}
{{repai}}`
  },
  {
    id: 'manguito_aberto',
    name: 'Reparo Aberto do Manguito Rotador',
    category: 'Ombro',
    color: 'ombro',
    corpo: `
PACIENTE EM [[posicao | CADEIRA DE PRAIA, DECUBITO LATERAL]] SOB [[anestesia | ANESTESIA GERAL, BLOQUEIO PLEXULAR]]
{{assepsia}}
SEM GARROTEAMENTO
INCISAO LONGITUDINAL SOBRE O ACROMIO [[lado | DIREITO, ESQUERDO]] COM EXTENSAO LATERAL
{{disseccao}}
DESINSERCAO PARCIAL DO MUSCULO DELTOIDE DO ACROMIO PARA EXPOSICAO DO ESPACO SUBACROMIAL
BURSECTOMIA SUBACROMIAL COM REMOCAO DA BURSA INFLAMADA
ACROMIOPLASTIA ANTERIOR COM RESSECCAO DA PORCAO INFERIOR DO ACROMIO COM SERRA OSCILANTE
[[biceps | , TENOTOMIA DO TENDAO DA CABECA LONGA DO BICEPS, TENOTOMIA E TENODESE DO TENDAO DA CABECA LONGA DO BICEPS NO SULCO INTERTUBERCULAR COM FIO ABSORVIVEL]]
IDENTIFICACAO DA LESAO DO MANGUITO ROTADOR COM AVALIACAO DA EXTENSAO E QUALIDADE TECIDUAL
LESAO DO TENDAO [[tendao | SUPRAESPINHAL, INFRAESPINHAL, SUBESCAPULAR, COMBINADA]] IDENTIFICADA
PREPARO DO LEITO TENDINEO NO TUBERCULO MAIOR COM DECORTICACAO DA SUPERFICIE OSSEA PARA ESTIMULO DE CICATRIZACAO
MOBILIZACAO DO COTO TENDINEO COM LIBERACAO DAS ADERENCIAS CAPSULARES SUPERIORES E INFERIORES
INSERCAO DE [[ancoras |# 2]] ANCORAS DE SUTURA NO TUBERCULO MAIOR [[lado]]
REPARO DO TENDAO COM TECNICA DE [[fileira | FILEIRA SIMPLES, DUPLA FILEIRA]] COM [[fio_reparo | FIO ABSORVIVEL, FIO NAO ABSORVIVEL]]
CONFIRMADA TENSAO ADEQUADA DO REPARO COM AMPLITUDE DE MOVIMENTO PASSIVA DO OMBRO
REINSERCAO DO DELTOIDE NO ACROMIO COM FIO ABSORVIVEL
{{lavagemExaustiva}}
{{suturaPlanos}}
SUTURA DE PELE COM NYLON
IMOBILIZACAO EM [[imobilizacao | TIPOIA, TIPOIA COM CINTO DE ROTACAO INTERNA, ORTESE ABDUTORA]]
{{curativo}}
{{repai}}`
  },

  /* =========================  MAO E PUNHO  =============================== */
  {
    id: 'dedo_gatilho',
    name: 'Dedo em Gatilho / Tenolise do Flexor',
    category: 'Mao e Punho',
    color: 'mao',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB BLOQUEIO PLEXULAR
{{assepsia}}
GARROTEAMENTO DE MEMBRO SUPERIOR [[lado | DIREITO, ESQUERDO]]
INCISAO LONGITUDINAL SOBRE POLIA A1 DO [[dedo | 1º, 2º, 3º, 4º, 5º]] DEDO, SEGUINDO LINHAS DA PREGA PALMAR
DISSECCAO POR PLANOS
VISUALIZACAO DA POLIA A1 ESPESSADA E TENDOES FLEXORES
ABERTURA DA POLIA A1 COM RESSECCAO PARCIAL DA MESMA
TENOLISE DO TENDAO FLEXOR NO TUNEL OSTEOFIBROSO COM LIBERACAO COMPLETA DO DESLIZAMENTO TENDINEO
HEMOSTASIA CUIDADOSA
SUTURA DE PELE COM [[fio_pele | NYLON 4-0]]
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'tenorrafia_extensor',
    name: 'Tenorrafia do Extensor / Reconstrucao Capsular e do Aparelho Extensor',
    category: 'Mao e Punho',
    color: 'mao',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB BLOQUEIO PLEXULAR
{{assepsia}}
GARROTEAMENTO DE MEMBRO SUPERIOR [[lado | ESQUERDO, DIREITO]]
INCISAO LONGITUDINAL DORSAL SOBRE O [[dedo | 4º, 1º, 2º, 3º, 5º]] QUIRODACTILO [[lado]]
DISSECCAO POR PLANOS E HEMOSTASIA
VISUALIZACAO DO TENDAO EXTENSOR DO [[dedo]] DEDO COM LESAO TENDINEA
IDENTIFICADO FRAGMENTO OSSEO NA FACE ARTICULAR DORSAL DO METACARPO COM LESAO CAPSULAR ASSOCIADA
RECONSTRUCAO DA CAPSULA ARTICULAR COM SUTURA COM FIO ABSORVIVEL
TENORRAFIA DO TENDAO EXTENSOR COM SUTURA EM KESSLER MODIFICADO E SUTURA CONTINUA EPITENDINEA COM FIO ABSORVIVEL
RECONSTRUCAO DO APARELHO EXTENSOR COM REPARO DAS BANDAS LATERAIS E CAPUZ EXTENSOR
HEMOSTASIA CUIDADOSA
SUTURA DE PELE COM [[fio_pele | NYLON 4-0]]
IMOBILIZACAO COM TALA GESSADA DORSAL EM POSICAO FUNCIONAL
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'tunel_carpo',
    name: 'Sindrome do Tunel do Carpo / Neurolise do Mediano',
    category: 'Mao e Punho',
    color: 'mao',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB BLOQUEIO PLEXULAR
{{assepsia}}
GARROTEAMENTO DE MEMBRO SUPERIOR [[lado | ESQUERDO, DIREITO]]
INCISAO EM FACE VOLAR DO PUNHO [[lado]] SEGUINDO LINHA TENAR MEDIAL
DISSECCAO POR PLANOS E HEMOSTASIA
ABERTURA DO LIGAMENTO TRANSVERSO DO CARPO COM RESSECCAO PARCIAL DO MESMO
IDENTIFICACAO DO NERVO MEDIANO COM ASPECTO ESPESSADO E SINAL DA AMPULHETA CARACTERISTICO
NEUROLISE INTERNA DO NERVO MEDIANO NO TUNEL OSTEOFIBROSO COM LIBERACAO COMPLETA DAS ADERENCIAS PERINEURAIS
[[tenossinovectomia | , IDENTIFICADA TENOSSINOVITE DOS TENDOES FLEXORES, TENOSSINOVECTOMIA DOS TENDOES FLEXORES COM RESSECCAO DO TECIDO SINOVIAL HIPERTROFIADO]]
CONFIRMADA FOLGA ADEQUADA DO TUNEL DO CARPO AO FINAL DO PROCEDIMENTO
HEMOSTASIA CUIDADOSA
SUTURA DE PELE COM [[fio_pele | NYLON 4-0]]
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'tunel_cubital',
    name: 'Sindrome do Tunel Cubital / Neurolise + Transposicao do Ulnar',
    category: 'Mao e Punho',
    color: 'mao',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB BLOQUEIO PLEXULAR
{{assepsia}}
GARROTEAMENTO DE MEMBRO SUPERIOR [[lado | DIREITO, ESQUERDO]]
INCISAO LONGITUDINAL MEDIAL AO NIVEL DO COTOVELO, SOBRE A GOTEIRA EPITROCLEO-OLECRANIANA
DISSECCAO POR PLANOS E HEMOSTASIA
IDENTIFICACAO DO NERVO ULNAR NO TUNEL CUBITAL
EVIDENCIADO NERVO ULNAR COM IMPORTANTE ESPESSAMENTO E ASPECTO FIBROTICO, COM EXTENSAS ADERENCIAS AO LONGO DE TODA A EXTENSAO DO TUNEL CUBITAL
IDENTIFICADA FIBROSE SIGNIFICATIVA A NIVEL DO SEPTO INTERMUSCULAR MEDIAL
MICRONEUROLISE DO NERVO ULNAR COM AUXILIO DE LUPA DE 4X DE AUMENTO, COM LIBERACAO MINUCIOSA DE TODAS AS ADERENCIAS PERINEURAIS E EPINEURAIS
TRANSPOSICAO [[transposicao | SUBMUSCULAR, SUBCUTANEA]] DO NERVO ULNAR COM POSICIONAMENTO DO NERVO EM LEITO ANTERIOR AO EPICONDILO MEDIAL
SUTURA DA FASCIA DO GRUPO MUSCULO-FLEXOR-PRONADOR SOBRE O NERVO TRANSPOSTO, FIXADA AO EPICONDILO MEDIAL
HEMOSTASIA CUIDADOSA
{{suturaPlanos}}
SUTURA DE PELE COM [[fio_pele | NYLON 4-0]]
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'dupuytren',
    name: 'Doenca de Dupuytren / Fasciectomia',
    category: 'Mao e Punho',
    color: 'mao',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB ANESTESIA PLEXULAR EM MEMBRO SUPERIOR [[lado | DIREITO, ESQUERDO]]
ASSEPSIA, ANTISSEPSIA E COLOCACAO DE CAMPOS ESTEREIS
GARROTE EM RAIZ DO BRACO [[lado]]
OBSERVADA CORDA EM FACE VOLAR DO [[raio | POLEGAR, 5º DEDO, 4º DEDO, 3º DEDO, 2º DEDO]] [[lado]], CAUSANDO LIMITACAO DA EXTENSAO
ACESSO DE BRUNER EM FACE VOLAR DO [[raio]] [[lado]], DISSECCAO POR PLANOS COM HEMOSTASIA CRITERIOSA
IDENTIFICADO ESPESSAMENTO DA FASCIA PALMAR FORMANDO CORDA FIBROSA; REALIZADA FASCIECTOMIA COM DISSECCAO CUIDADOSA, OBTENDO EXTENSAO COMPLETA
IDENTIFICADOS NERVOS DIGITAIS RADIAL E ULNAR COM TRAVES FIBROSAS ENVOLVENDO-OS; REALIZADA MICRONEUROLISE SOB MAGNIFICACAO COM LUPA CIRURGICA 4.3X
RETIRADO GARROTE COM BOA PERFUSAO DISTAL, SEM SANGRAMENTO EXCESSIVO
REVISAO DA HEMOSTASIA E LIMPEZA COM SF 0,9%
SUTURA DA PELE COM MONONYLON 4-0, COM AVANCO DE RETALHOS EM Z PARA ADEQUADA COBERTURA DEVIDO AO GANHO DE EXTENSAO
{{curativo}}
{{repai}}`
  },
  {
    id: 'radio_distal_kwire',
    name: 'Fratura do Radio Distal / Reducao Incruenta e Fixacao Percutanea',
    category: 'Mao e Punho',
    color: 'mao',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB BLOQUEIO PLEXULAR
{{assepsia}}
GARROTEAMENTO DO MEMBRO SUPERIOR [[lado | DIREITO, ESQUERDO]]
REDUCAO INCRUENTA DA FRATURA DO RADIO DISTAL [[lado]] POR MANOBRA FECHADA SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP E PERFIL
CONFIRMADA REDUCAO SATISFATORIA AO FLUOROSCOPIO
FIXACAO PERCUTANEA COM [[fios_radial |# 2]] FIOS DE KIRSCHNER INSERIDOS PROXIMALMENTE AO ESTILOIDE RADIAL EM DIRECAO AO CORTEX ULNAR DO RADIO
FIXACAO PERCUTANEA COM [[fios_lister |# 1]] FIO DE KIRSCHNER INSERIDO ULNAR AO TUBERCULO DE LISTER EM DIRECAO AO CORTEX VOLAR DO RADIO
CONTROLE FLUOROSCOPICO FINAL NAS INCIDENCIAS AP E PERFIL CONFIRMANDO REDUCAO MANTIDA E POSICIONAMENTO ADEQUADO DOS FIOS
IMOBILIZACAO COM TALA GESSADA ANTEBRAQUIOPALMAR
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },

  /* ============================  TRAUMA  ================================= */
  {
    id: 'subtrocanterica_haste',
    name: 'Fratura Subtrocanterica / Haste Cefalomedular Longa',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]] COM MESA DE TRACAO EM MEMBRO INFERIOR [[lado | DIREITO, ESQUERDO]]
REDUCAO DE FRATURA POR MEIO DE MANOBRA
OBSERVADA REDUCAO COM AUXILIO DE FLUOROSCOPIO
{{assepsia}}
INCISAO SOBRE TROCANTER MAIOR [[lado]]
DIVULSAO POR PLANOS
INSERCAO DE FIO GUIA INTRAMEDULAR
OBSERVADO POSICIONAMENTO ADEQUADO AO FLUOROSCOPIO NAS INCIDENCIAS AP E PERFIL
FRESAGEM INICIAL COM PROTECAO DE PARTES MOLES
PASSAGEM DE HASTE CEFALOMEDULAR LONGA [[haste=Haste |+ 10X360, 11X380, 10X380]] MM COM AUXILIO DE GUIA
INSERCAO DE FIO GUIA PARA BLOQUEIO CEFALICO
OBSERVADO POSICIONAMENTO ADEQUADO AO FLUOROSCOPIO NAS INCIDENCIAS AP E PERFIL
FRESAGEM DO TRAJETO E BLOQUEIO COM [[cefalico=Parafuso cefalico |+ PARAFUSO DE COMPRESSAO CEFALICO 80 MM, PARAFUSO DESLIZANTE CEFALICO 95 MM]]
BLOQUEIO DISTAL COM [[distal=Bloqueio distal |+ PARAFUSO 30 MM, PARAFUSO 35 MM]]
CONTROLE FLUOROSCOPICO FINAL COM REDUCAO DENTRO DO POSSIVEL
{{lavagem}}
{{rafia}}
{{curativo}}
RETIRADA DA MESA DE TRACAO
{{repai}}`
  },
  {
    id: 'transtrocanterica_haste',
    name: 'Fratura Transtrocanterica / Haste Cefalomedular Bloqueada',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]] COM MESA DE TRACAO
{{assepsia}}
REDUCAO DA FRATURA POR MANOBRA SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP E PERFIL
OBSERVADA REDUCAO SATISFATORIA DA FRATURA TRANSTROCANTERICA AO FLUOROSCOPIO
INCISAO LONGITUDINAL SOBRE O TROCANTER MAIOR [[lado | DIREITO, ESQUERDO]]
DIVULSAO POR PLANOS COM EXPOSICAO DO PONTO DE ENTRADA NO TROCANTER MAIOR
INSERCAO DE FIO GUIA INTRAMEDULAR SOB CONTROLE FLUOROSCOPICO
OBSERVADO POSICIONAMENTO ADEQUADO DO FIO GUIA NAS INCIDENCIAS AP E PERFIL
FRESAGEM INICIAL COM PROTECAO DE PARTES MOLES
PASSAGEM DE HASTE CEFALOMEDULAR [[haste=Haste |+ 11X170, 11X180, 10X170]] MM COM AUXILIO DE GUIA INTRODUTOR
INSERCAO DE FIO GUIA PARA BLOQUEIO CEFALICO
OBSERVADO POSICIONAMENTO ADEQUADO AO FLUOROSCOPIO NAS INCIDENCIAS AP E PERFIL
FRESAGEM DO TRAJETO CEFALICO E INSERCAO DE [[cefalico=Parafuso cefalico |+ PARAFUSO CEFALICO, PARAFUSO DESLIZANTE CEFALICO 95 MM]]
BLOQUEIO DISTAL COM [[distal=Bloqueio distal |+ PARAFUSO DE 35 MM, PARAFUSO 30 MM]] SOB CONTROLE FLUOROSCOPICO
{{fluoroFinalImplante}}
{{lavagem}}
{{rafia}}
SUTURA DE PELE
{{curativo}}
RETIRADA DA MESA DE TRACAO
{{repai}}`
  },
  {
    id: 'tibia_haste',
    name: 'Fratura Diafisaria da Tibia / Haste Intramedular Bloqueada',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]]
{{assepsia}}
REDUCAO DA FRATURA POR MANOBRA SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP E PERFIL
INCISAO LONGITUDINAL [[acesso | PARAPATELAR MEDIAL, SUPRAPATELAR, TRANSPATELAR]] AO NIVEL DO JOELHO [[lado | DIREITO, ESQUERDO]]
DIVULSAO POR PLANOS COM EXPOSICAO DO PONTO DE ENTRADA TIBIAL
INSERCAO DE FIO GUIA INTRAMEDULAR SOB CONTROLE FLUOROSCOPICO
OBSERVADO POSICIONAMENTO ADEQUADO DO FIO GUIA NAS INCIDENCIAS AP E PERFIL
FRESAGEM PROGRESSIVA DO CANAL MEDULAR COM PROTECAO DE PARTES MOLES
PASSAGEM DE HASTE INTRAMEDULAR BLOQUEADA [[haste=Haste |+ 10X380, 9X330, 10X360]] MM COM AUXILIO DE GUIA INTRODUTOR
OBSERVADO POSICIONAMENTO ADEQUADO DA HASTE AO FLUOROSCOPIO NAS INCIDENCIAS AP E PERFIL
BLOQUEIO PROXIMAL COM [[bloq_prox |# 2]] PARAFUSOS GUIADOS PELO DISPOSITIVO DE MIRA
BLOQUEIO DISTAL COM [[bloq_distal |# 2]] PARAFUSOS SOB CONTROLE FLUOROSCOPICO COM TECNICA DE MAO LIVRE
{{fluoroFinalImplante}}
{{lavagem}}
{{rafia}}
SUTURA DE PELE COM NYLON
{{curativo}}
{{repai}}`
  },
  {
    id: 'femur_haste_retrograda',
    name: 'Fratura Diafisaria do Femur / Haste Intramedular Retrograda',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]]
{{assepsia}}
REDUCAO DA FRATURA POR MANOBRA SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP E PERFIL
INCISAO LONGITUDINAL TRANSPATELAR AO NIVEL DO JOELHO [[lado | DIREITO, ESQUERDO]]
DIVULSAO POR PLANOS COM ABERTURA DO TENDAO PATELAR NO SENTIDO DE SUAS FIBRAS
EXPOSICAO DO PONTO DE ENTRADA FEMORAL DISTAL NA FOSSA INTERCONDILAR
INSERCAO DE FIO GUIA INTRAMEDULAR RETROGRADO SOB CONTROLE FLUOROSCOPICO
OBSERVADO POSICIONAMENTO ADEQUADO DO FIO GUIA NAS INCIDENCIAS AP E PERFIL
FRESAGEM PROGRESSIVA DO CANAL MEDULAR FEMORAL EM SENTIDO RETROGRADO COM PROTECAO DE PARTES MOLES
PASSAGEM DE HASTE INTRAMEDULAR RETROGRADA BLOQUEADA [[haste=Haste |+ 9X330]] MM COM AUXILIO DE GUIA INTRODUTOR
OBSERVADO POSICIONAMENTO ADEQUADO DA HASTE AO FLUOROSCOPIO NAS INCIDENCIAS AP E PERFIL
BLOQUEIO DISTAL COM [[bloq_distal |# 2]] PARAFUSOS GUIADOS PELO DISPOSITIVO DE MIRA
BLOQUEIO PROXIMAL COM [[bloq_prox |# 2]] PARAFUSOS SOB CONTROLE FLUOROSCOPICO COM TECNICA DE MAO LIVRE
{{fluoroFinalImplante}}
{{lavagem}}
SUTURA DO TENDAO PATELAR COM VICRYL
{{rafia}}
SUTURA DE PELE COM NYLON
{{curativo}}
{{repai}}`
  },
  {
    id: 'fix_externo_femur',
    name: 'Fixador Externo Modular Tubo a Tubo / Femur',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | RAQUIANESTESIA, ANESTESIA GERAL]]
{{assepsia}}
REDUCAO DA FRATURA POR MANOBRA SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP E PERFIL
INCISOES PERCUTANEAS PARA INSERCAO DOS PINOS DE SCHANZ
INSERCAO DE [[pinos_prox |# 2]] PINOS DE SCHANZ [[schanz | 6,0 MM, 5,0 MM]] NO FRAGMENTO PROXIMAL DO FEMUR [[lado | DIREITO, ESQUERDO]] SOB CONTROLE FLUOROSCOPICO
INSERCAO DE [[pinos_dist |# 2]] PINOS DE SCHANZ [[schanz]] NO FRAGMENTO DISTAL DO FEMUR [[lado]] SOB CONTROLE FLUOROSCOPICO
MONTAGEM DO FIXADOR EXTERNO MODULAR TUBO A TUBO COM CONEXAO E ESTABILIZACAO DOS PINOS
CONTROLE FLUOROSCOPICO FINAL NAS INCIDENCIAS AP E PERFIL CONFIRMANDO REDUCAO E POSICIONAMENTO ADEQUADO DO FIXADOR
CURATIVO ESTERIL NOS SITIOS DE INSERCAO DOS PINOS
{{repai}}`
  },
  {
    id: 'fix_externo_umero_distal',
    name: 'Fixador Externo Modular Tubo a Tubo / Umero Distal',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB BLOQUEIO PLEXULAR
{{assepsia}}
GARROTEAMENTO DO MEMBRO SUPERIOR [[lado | DIREITO, ESQUERDO]]
INCISOES ABERTAS SOBRE O UMERO [[lado]] COM DISSECCAO POR PLANOS ATE O OSSO, COM VISUALIZACAO DIRETA DAS ESTRUTURAS NEUROVASCULARES ADJACENTES
IDENTIFICACAO E PROTECAO DOS NERVOS ADJACENTES AO LONGO DO TRAJETO DE INSERCAO
INSERCAO DE [[pinos_umero |# 2]] PINOS DE SCHANZ NO SEGMENTO UMERAL PROXIMAL A FRATURA SOB VISUALIZACAO DIRETA E CONTROLE FLUOROSCOPICO
INCISOES PERCUTANEAS SOBRE A ULNA [[lado]]
INSERCAO DE [[pinos_ulna |# 2]] PINOS DE SCHANZ NA ULNA SOB CONTROLE FLUOROSCOPICO
MONTAGEM DO FIXADOR EXTERNO MODULAR TUBO A TUBO COM CONEXAO DOS PINOS UMERAIS AOS PINOS ULNARES
REDUCAO DA FRATURA DO UMERO DISTAL E ESTABILIZACAO DO CONJUNTO
CONTROLE FLUOROSCOPICO FINAL NAS INCIDENCIAS AP E PERFIL CONFIRMANDO REDUCAO E POSICIONAMENTO ADEQUADO DO FIXADOR
{{lavagem}}
SUTURA DE PELE NOS SITIOS DE ACESSO ABERTO COM NYLON
CURATIVO ESTERIL NOS SITIOS DE INSERCAO DOS PINOS E FERIDAS OPERATORIAS
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
IMOBILIZACAO EM TIPOIA
{{repai}}`
  },
  {
    id: 'fix_externo_tibia',
    name: 'Fixador Externo / Tibia e Tornozelo',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL HORIZONTAL SOB RAQUIANESTESIA
{{assepsia}}
[[montagem | ACESSO ANTERIOR EM CRISTA DE TIBIA PROXIMAIS E DISTAIS AO FOCO DE FRATURA, ACESSO ANTERIOR EM CRISTA DE TIBIA E ACESSO MEDIAL EM CALCANEO E BASE DE 1º METATARSIANO PARA MONTAGEM TRANSARTICULAR]]
REALIZACAO DE CANAL COM PERFURADOR PARA PASSAGEM DE PINOS DE SCHANZ INTRAOSSEOS NOS RESPECTIVOS ACESSOS
COLOCACAO DE PINOS DE SCHANZ [[schanz | 6.0 MM, 5.0 MM]] EM RESPECTIVOS ACESSOS
MONTAGEM DE FIXADOR EXTERNO [[tipo | LINEAR, TRANSARTICULAR]] TUBO A TUBO
REDUCAO DE FRATURA SOB AUXILIO DE RADIOSCOPIA
FIXACAO DO FIXADOR EXTERNO COM APERTO DE PARAFUSOS
VERIFICADA BOA REDUCAO COM AUXILIO DE RADIOSCOPIA
LIMPEZA COM DEGERMANTE E SF 0,9%
CURATIVO ESTERIL NOS SITIOS DE INSERCAO DOS PINOS
{{repai}}`
  },
  {
    id: 'parafuso_sacroiliaco',
    name: 'Fixacao Percutanea Sacroiliaca / Parafuso Sacroiliaco',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB RAQUIANESTESIA
{{assepsia}}
POSICIONAMENTO DO FLUOROSCOPIO PARA OBTENCAO DAS INCIDENCIAS AP, INLET, OUTLET E PERFIL DA PELVE
IDENTIFICACAO DA LINHA DO ANEL PELVICO AO FLUOROSCOPIO COMO REFERENCIA PARA O TRAJETO DO PARAFUSO SACROILIACO
INCISAO PERCUTANEA SOBRE A REGIAO GLUTEA [[lado | ESQUERDA, DIREITA]] NO PONTO DE ENTRADA DO PARAFUSO SACROILIACO
INSERCAO DO FIO DE STEINMANN COMO FIO GUIA SOB CONTROLE FLUOROSCOPICO CONTINUO NAS INCIDENCIAS AP, INLET E OUTLET
AVANCO CUIDADOSO DO FIO GUIA ATRAVES DA ALA DO SACRO ATE POSICIONAMENTO ADEQUADO NO CORPO DE S1, RESPEITANDO OS LIMITES OSSEOS
CONTROLE FLUOROSCOPICO CONFIRMANDO POSICIONAMENTO SATISFATORIO DO FIO GUIA EM TODAS AS INCIDENCIAS
MEDICAO DO COMPRIMENTO DO TRAJETO PARA DIMENSIONAMENTO DO IMPLANTE
FRESAGEM DO TRAJETO SOBRE O FIO GUIA
INSERCAO DE PARAFUSO SACROILIACO DE [[parafuso |+ 90 MM]] COM ARRUELA
CONTROLE FLUOROSCOPICO FINAL NAS INCIDENCIAS AP, INLET, OUTLET E PERFIL CONFIRMANDO POSICIONAMENTO ADEQUADO DO PARAFUSO E REDUCAO SATISFATORIA
{{lavagem}}
SUTURA DE PELE COM NYLON
{{curativo}}
{{repai}}`
  },
  {
    id: 'umero_distal_rafi',
    name: 'Fratura do Umero Distal / RAFI / Acesso Posterior',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO [[decubito | LATERAL, VENTRAL]] SOB [[anestesia | ANESTESIA GERAL, BLOQUEIO PLEXULAR]]
{{assepsia}}
GARROTEAMENTO DO MEMBRO SUPERIOR [[lado | DIREITO, ESQUERDO]]
INCISAO LONGITUDINAL POSTERIOR SOBRE O COTOVELO [[lado]]
{{disseccao}}
IDENTIFICACAO E PROTECAO DO NERVO ULNAR COM [[ulnar | NEUROLISE E TRANSPOSICAO ANTERIOR, MANUTENCAO IN SITU]]
ACESSO A FRATURA POR [[via | OSTEOTOMIA DO OLECRANO, ABORDAGEM PARATRICIPITAL, ABORDAGEM TRICEPS SPLITTING]]
IDENTIFICACAO DOS FRAGMENTOS DA FRATURA COM LIMPEZA DO FOCO E REMOCAO DE COAGULOS
REDUCAO DOS FRAGMENTOS ARTICULARES SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP E PERFIL
FIXACAO PROVISORIA COM FIOS DE KIRSCHNER
FIXACAO DEFINITIVA COM PLACAS EM CONFIGURACAO [[config | PARALELA, PERPENDICULAR]]
INSERCAO DE PLACA NA COLUNA LATERAL DO UMERO DISTAL COM [[parafusos_lat |# 3]] PARAFUSOS
INSERCAO DE PLACA NA COLUNA MEDIAL DO UMERO DISTAL COM [[parafusos_med |# 3]] PARAFUSOS
CONTROLE FLUOROSCOPICO CONFIRMANDO REDUCAO ARTICULAR E POSICIONAMENTO ADEQUADO DOS IMPLANTES
TESTE DE ESTABILIDADE DA FIXACAO COM MOBILIZACAO PASSIVA DO COTOVELO
[[olecrano | , OSTEOSSINTESE DO OLECRANO COM FIOS DE KIRSCHNER E BANDA DE TENSAO, OSTEOSSINTESE DO OLECRANO COM PLACA]]
{{lavagemExaustiva}}
{{suturaPlanos}}
SUTURA DE PELE COM NYLON
IMOBILIZACAO COM TALA GESSADA POSTERIOR EM POSICAO FUNCIONAL
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'deslizamento_fisario_radio',
    name: 'Deslizamento Fisario do Radio Distal / Fixacao Percutanea',
    category: 'Trauma',
    color: 'trauma',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB BLOQUEIO PLEXULAR
{{assepsia}}
GARROTEAMENTO DE MEMBRO SUPERIOR [[lado | ESQUERDO, DIREITO]]
REDUCAO DO DESLIZAMENTO FISARIO DO RADIO DISTAL [[lado]] POR MANOBRA FECHADA
CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP E PERFIL CONFIRMANDO REDUCAO SATISFATORIA DA FISE
FIXACAO PERCUTANEA COM [[fios |# 1]] FIO DE KIRSCHNER [[calibre | 2,0 MM, 1,5 MM, 1,8 MM]] INSERIDO PELO TUBERCULO RADIAL EM DIRECAO A FISE
CONTROLE FLUOROSCOPICO FINAL NAS INCIDENCIAS AP E PERFIL CONFIRMANDO REDUCAO E POSICIONAMENTO ADEQUADO DO FIO
IMOBILIZACAO COM TALA GESSADA ANTEBRAQUIOPALMAR
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },

  /* =========================  PE E TORNOZELO  =========================== */
  {
    id: 'maleolo_lateral_rafi',
    name: 'Fratura do Maleolo Lateral / RAFI',
    category: 'Pe e Tornozelo',
    color: 'pe',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB RAQUIANESTESIA
{{assepsia}}
[[garrote | GARROTEAMENTO DO MEMBRO INFERIOR, SEM GARROTEAMENTO]] [[lado | DIREITO, ESQUERDO]]
INCISAO LONGITUDINAL LATERAL SOBRE O MALEOLO LATERAL [[lado]] COM DISSECCAO CUIDADOSA E PROTECAO DAS ESTRUTURAS NEUROVASCULARES ADJACENTES
{{disseccao}}
IDENTIFICACAO DO FOCO DE FRATURA DO MALEOLO LATERAL
REDUCAO DA FRATURA SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP, PERFIL E MORTISE
FIXACAO COM PLACA [[placa | 1/3 DE CANO DE 7 FUROS, 1/3 DE CANO, 1/3 DE CANO DE 8 FUROS]] POSICIONADA NA FACE LATERAL DA FIBULA
INSERCAO DE [[parafusos |# 6]] PARAFUSOS CORTICAIS
[[sindesmose | , IDENTIFICADA LESAO DA SINDESMOSE TIBIOFIBULAR COM INSTABILIDADE; INSERCAO DE PARAFUSO TRANSINDESIMAL PARA ESTABILIZACAO DA SINDESMOSE ACIMA DA LINHA ARTICULAR DO TORNOZELO]]
CONTROLE FLUOROSCOPICO FINAL NAS INCIDENCIAS AP, PERFIL E MORTISE CONFIRMANDO REDUCAO E POSICIONAMENTO SATISFATORIO DOS IMPLANTES
{{lavagem}}
{{suturaPlanos}}
SUTURA DE PELE COM NYLON
IMOBILIZACAO COM TALA GESSADA SUROPODALICA
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'bimaleolar_rafi',
    name: 'Fratura Bimaleolar do Tornozelo / RAFI',
    category: 'Pe e Tornozelo',
    color: 'pe',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB RAQUIANESTESIA
{{assepsia}}
GARROTEAMENTO DO MEMBRO INFERIOR [[lado | ESQUERDO, DIREITO]]
INCISAO LONGITUDINAL LATERAL SOBRE O MALEOLO LATERAL [[lado]]
{{disseccao}}
IDENTIFICACAO E REDUCAO DA FRATURA DO MALEOLO LATERAL SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP, PERFIL E MORTISE
FIXACAO COM PLACA 1/3 DE CANO POSICIONADA NA FACE LATERAL DA FIBULA E INSERCAO DE PARAFUSOS CORTICAIS
INCISAO LONGITUDINAL SOBRE O MALEOLO MEDIAL [[lado]]
IDENTIFICACAO E REDUCAO DA FRATURA DO MALEOLO MEDIAL SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP, PERFIL E MORTISE
FIXACAO DO MALEOLO MEDIAL COM [[fixacao_medial | PARAFUSO ESPONJOSO PARCIALMENTE ROSQUEADO 3,5X50 MM, PARAFUSO CORTICAL, PLACA DE RECONSTRUCAO]]
CONTROLE FLUOROSCOPICO FINAL DO TORNOZELO [[lado]] NAS INCIDENCIAS AP, PERFIL E MORTISE CONFIRMANDO REDUCAO GLOBAL SATISFATORIA E POSICIONAMENTO ADEQUADO DE TODOS OS IMPLANTES
{{lavagem}}
{{suturaPlanos}}
SUTURA DE PELE COM NYLON
IMOBILIZACAO COM TALA GESSADA SUROPODALICA
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'lisfranc',
    name: 'Fratura-Luxacao de Lisfranc / RAFI',
    category: 'Pe e Tornozelo',
    color: 'pe',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB RAQUIANESTESIA
{{assepsia}}
GARROTEAMENTO DO MEMBRO INFERIOR [[lado | DIREITO, ESQUERDO]]
INCISAO LONGITUDINAL DORSAL SOBRE O MEDIOPE COM ACESSO A ARTICULACAO DE LISFRANC
{{disseccao}}
IDENTIFICACAO DA LESAO DE LISFRANC COM INSTABILIDADE DA COLUNA MEDIAL E FRATURA DO [[metatarso | 2º, 1º, 3º]] METATARSO
REDUCAO DA FRATURA-LUXACAO DE LISFRANC SOB CONTROLE FLUOROSCOPICO NAS INCIDENCIAS AP, PERFIL E OBLIQUA DO PE
INSERCAO DE PARAFUSO ESPONJOSO DA CUNHA MEDIAL PARA A CUNHA INTERMEDIA PARA ESTABILIZACAO DA COLUNA MEDIAL DE LISFRANC
INSERCAO DE PARAFUSO ESPONJOSO DA CUNHA INTERMEDIA PARA O [[metatarso]] METATARSO PARA ESTABILIZACAO DA COLUNA CENTRAL DE LISFRANC
FIXACAO COMPLEMENTAR DO [[metatarso]] METATARSO COM FIO DE KIRSCHNER [[calibre | 1,5 MM, 1,8 MM]]
CONTROLE FLUOROSCOPICO FINAL NAS INCIDENCIAS AP, PERFIL E OBLIQUA DO PE CONFIRMANDO REDUCAO GLOBAL SATISFATORIA E POSICIONAMENTO ADEQUADO DOS IMPLANTES
{{lavagem}}
{{suturaPlanos}}
SUTURA DE PELE COM NYLON
IMOBILIZACAO COM TALA GESSADA SUROPODALICA
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'hallux_scarf',
    name: 'Hallux Valgus / Osteotomia de Scarf / Parafuso de Herbert',
    category: 'Pe e Tornozelo',
    color: 'pe',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB RAQUIANESTESIA
{{assepsia}}
GARROTEAMENTO DO MEMBRO INFERIOR [[lado | ESQUERDO, DIREITO]]
INCISAO MEDIAL SOBRE O 1º METATARSO [[lado]]
{{disseccao}}
EXPOSICAO DA ARTICULACAO METATARSOFALANGICA DO HALUX E DO 1º METATARSO
CAPSULOTOMIA MEDIAL COM EXPOSICAO DA CABECA DO 1º METATARSO
RESSECCAO DA EXOSTOSE MEDIAL DA CABECA DO 1º METATARSO
OSTEOTOMIA DE SCARF DO 1º METATARSO [[lado]] PARA CORRECAO DO HALLUX VALGUS
TRANSLACAO E CORRECAO DO FRAGMENTO DISTAL COM REDUCAO DO ANGULO INTERMETATARSAL
FIXACAO COM [[parafusos |# 1]] PARAFUSO DE HERBERT [[tamanho |+ 28 MM]]
CONTROLE FLUOROSCOPICO CONFIRMANDO POSICIONAMENTO ADEQUADO DO PARAFUSO E CORRECAO SATISFATORIA
CAPSULOPLASTIA MEDIAL COM REFORCO CAPSULAR E CORRECAO DO ALINHAMENTO DO HALUX
{{lavagem}}
{{suturaPlanos}}
SUTURA DE PELE COM NYLON
CURATIVO COMPRESSIVO ESPECIFICO PARA HALLUX VALGUS COM MANUTENCAO DA CORRECAO
CALCADO SANDALIA DE BARUK NO POS-OPERATORIO IMEDIATO
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'aquiles_fhl',
    name: 'Ruptura Cronica do Tendao Calcaneo / Transposicao do FHL',
    category: 'Pe e Tornozelo',
    color: 'pe',
    corpo: `
PACIENTE EM DECUBITO VENTRAL SOB RAQUIANESTESIA
{{assepsia}}
GARROTEAMENTO DO MEMBRO INFERIOR [[lado | DIREITO, ESQUERDO]]
INCISAO LONGITUDINAL POSTEROLATERAL SOBRE O TENDAO CALCANEO
{{disseccao}}
IDENTIFICACAO E PROTECAO DO FEIXE NEUROVASCULAR ADJACENTE AO LONGO DE TODO O ACESSO
IDENTIFICACAO DA RUPTURA CRONICA DO TENDAO CALCANEO COM AVALIACAO DA EXTENSAO DA LESAO E QUALIDADE DO TECIDO REMANESCENTE
TENOLISE DO TENDAO FLEXOR LONGO DO HALUX COM LIBERACAO CUIDADOSA DAS ADERENCIAS
SECCAO DO TENDAO FLEXOR LONGO DO HALUX NO NIVEL MAIS DISTAL POSSIVEL PARA OBTENCAO DE COMPRIMENTO ADEQUADO
SUTURA DO COTO DISTAL DO FLEXOR LONGO DO HALUX COM FIO ABSORVIVEL PARA PROTECAO DA FUNCAO RESIDUAL
FRESAGEM DO CALCANEO COM CRIACAO DE TUNEL TRANSCALCANEO
PASSAGEM DO TENDAO FLEXOR LONGO DO HALUX PELO TUNEL TRANSCALCANEO
FIXACAO DO TENDAO TRANSPOSTO COM PARAFUSO DE INTERFERENCIA [[parafuso |+ 7X20 MM]] COM PE POSICIONADO EM EQUINO MODERADO PARA TENSIONAMENTO ADEQUADO
SUTURA DO TENDAO TRANSPOSTO AO COTO REMANESCENTE DO TENDAO CALCANEO COM REFORCO DA RECONSTRUCAO
CONFIRMADA TENSAO ADEQUADA COM TESTE DE MOBILIDADE PASSIVA DO TORNOZELO
{{lavagemExaustiva}}
SUTURA DO SUBCUTANEO COM VICRYL
SUTURA DE PELE COM NYLON 3.0
IMOBILIZACAO COM TALA GESSADA SUROPODALICA COM PE EM EQUINO MODERADO
{{curativo}}
SOLTURA DO GARROTE COM BOA REPERFUSAO DO MEMBRO CONFIRMADA
{{repai}}`
  },
  {
    id: 'ponseti_tenotomia',
    name: 'Tenotomia do Tendao Calcaneo / Ponseti',
    category: 'Pe e Tornozelo',
    color: 'pe',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB [[anestesia | SEDACAO, RAQUIANESTESIA, ANESTESIA GERAL]]
{{assepsia}}
INCISAO PERCUTANEA SOBRE O TENDAO CALCANEO [[lado | DIREITO, ESQUERDO, BILATERAL]] NA TRANSICAO MUSCULO-TENDINEA
TENOTOMIA PERCUTANEA COMPLETA DO TENDAO CALCANEO [[lado]] COM BISTURI NUMERO 15
CONFIRMADA TENOTOMIA COMPLETA COM DORSIFLEXAO DO TORNOZELO ACIMA DE 15 GRAUS
APLICACAO DE GESSO [[gesso | INGUINOPODALICO, SUROPODALICO]] COM PE EM POSICAO CORRIGIDA
{{curativo}}
{{repai}}`
  },

  /* ===========================  ONCOLOGIA  ============================== */
  {
    id: 'coa_embolizacao',
    name: 'Cisto Osseo Aneurismatico / Embolizacao, Drenagem e Biopsia',
    category: 'Oncologia',
    color: 'onco',
    corpo: `
PACIENTE EM DECUBITO DORSAL SOB SEDACAO
{{assepsia}}
INFILTRACAO LOCAL COM LIDOCAINA PARA CONTROLE DA DOR
ACESSO PERCUTANEO AO CISTO OSSEO ANEURISMATICO DO [[local | UMERO DISTAL, UMERO PROXIMAL, FEMUR PROXIMAL, TIBIA PROXIMAL]] [[lado | DIREITO, ESQUERDO]] COM AUXILIO DE AGULHA DE TREFINA SOB CONTROLE FLUOROSCOPICO
DRENAGEM DO CONTEUDO CISTICO COM SAIDA DE APROXIMADAMENTE [[volume | 140]] ML DE CONTEUDO HEMATICO CARACTERISTICO DE CISTO OSSEO ANEURISMATICO
COLETA DE [[fragmentos |# 2]] FRAGMENTOS DE TECIDO CISTICO PARA ANALISE ANATOMOPATOLOGICA
EMBOLIZACAO DA CAVIDADE CISTICA COM INJECAO DO AGENTE EMBOLIZANTE
INCISAO NAO FECHADA, MANTIDA ABERTA PARA DRENAGEM
CURATIVO SIMPLES
IMOBILIZACAO EM TIPOIA PARA CONFORTO
{{repai}}`
  },

  /* ============================  OUTROS  ================================ */
  {
    id: 'livre',
    name: 'Descricao Livre',
    category: 'Outros',
    color: 'livre',
    freeOnly: true,
    corpo: ``
  }

];

/* Exposicao para o app (navegador) e para testes (node) */
if (typeof window !== 'undefined') {
  window.SURGERIES = SURGERIES;
  window.BLOCOS = BLOCOS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SURGERIES, BLOCOS };
}
